---
- hosts: all
  become: true
  vars_files:
    - config.yaml
    
  tasks:
    - name: Install latest Python3 and pip3
      apt:
        name:
          - python3
          - python3-pip
        state: latest
        update_cache: yes

    - name: Set pip3 as default pip
      alternatives:
        name: pip
        link: /usr/bin/pip
        path: /usr/bin/pip3

    - name: Set python3 as default python
      alternatives:
        name: python
        link: /usr/bin/python
        path: /usr/bin/python3

    - name: Install Java OpenJDK
      apt:
        name: openjdk-21-jdk
        state: latest

